version: '3.8'

services:
  uptime-kuma:
    container_name: uptime-kuma-full-build
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    image: uptime-kuma:local-full
    restart: always
    ports:
      - "80:3001"

    volumes:
      - ./data:/app/data
      - ./server:/app/server
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./public:/app/public
