name: Deploy Frontend

on:
  push:
    branches:
      - master
  workflow_dispatch: {}
jobs:

  deploy:
    runs-on: ubuntu-latest

    # Configure Environment
    environment:
      name: deployment
      url: http://${{ secrets.FRONTEND_HOST }}
      permissions:
        contents: read
    steps:
      - name: Execute Remote Deployment via SSH
        uses: appleboy/ssh-action@master
        env:
          # Construct dynamic variables from GitHub Context
          GIT_REPO: "https://oauth2:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git"
          GIT_BRANCH: "${{ github.ref_name }}"
          TARGET_DIR: "/home/ubuntu/frontend"
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          # Pass environment variables to the remote script
          envs: GIT_REPO,GIT_BRANCH,TARGET_DIR
          script: |
            echo "🚀 Starting Deployment Logic..."
            echo "repo: $GIT_REPO"
            echo "branch: $GIT_BRANCH"

            # 1. Check if target directory exists
            if [ ! -d "$TARGET_DIR" ]; then
              echo "📂 Directory not found. Creating it..."
              mkdir -p $TARGET_DIR
            fi

            # 2. Fetch Code (Clone or Pull)
            if [ -d "$TARGET_DIR/.git" ]; then
              echo "🔄 Repository exists. Pulling latest changes..."
              cd $TARGET_DIR
              git fetch origin
              # Reset to the specific branch triggered in GitHub Actions
              git reset --hard origin/$GIT_BRANCH
            else
              echo "⬇️ Cloning repository from scratch..."
              git clone -b $GIT_BRANCH $GIT_REPO $TARGET_DIR
              cd $TARGET_DIR
            fi

            # 3. Build and Run Docker
            echo "🐳 Building Docker Image on Server..."
            
            # Ensure previous containers are down
            sudo docker compose down
            
            # Rebuild and start
            sudo docker compose up -d --build --remove-orphans

            echo "✅ Deployment Completed Successfully!"

      - name: Job Summary
        run: |
          echo "### 🚀 Deployment Finished!" >> $GITHUB_STEP_SUMMARY
          echo "✅ **Status:** Success" >> $GITHUB_STEP_SUMMARY
          echo "🌿 **Branch:** ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "🌍 **Live URL:** [http://${{ secrets.FRONTEND_HOST }}](http://${{ secrets.FRONTEND_HOST }})" >> $GITHUB_STEP_SUMMARY
